# Generated by Django 3.2.6 on 2021-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEstudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
