# Generated by Django 3.2.6 on 2021-08-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEstudiantes', '0002_auto_20210826_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEstudiantes.grupos'),
        ),
    ]
