# Generated by Django 3.2.6 on 2021-08-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEstudiantes', '0003_alter_estudiantes_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
    ]
