# Generated by Django 3.2.6 on 2021-08-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEstudiantes', '0004_alter_estudiantes_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEstudiantes.grupos'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='sexo',
            field=models.BooleanField(),
        ),
    ]
