# Generated by Django 3.2.6 on 2021-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEstudiantes', '0005_auto_20210827_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='profesorGuia',
            field=models.CharField(choices=[('Profesor 1', 'Profesor 1'), ('Profesor 2', 'Profesor 2'), ('Profesor 3', 'Profesor 3'), ('Profesor 4', 'Profesor 4'), ('Profesor 5', 'Profesor 5')], default='Profesor 1', max_length=50),
        ),
    ]
