# Generated by Django 3.2.6 on 2021-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEstudiantes', '0006_alter_grupos_profesorguia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ciudadNacimiento',
            field=models.CharField(choices=[('Ciudad 1', 'Ciudad 1'), ('Ciudad 2', 'Ciudad 2'), ('Ciudad 3', 'Ciudad 3'), ('Ciudad 4', 'Ciudad 4'), ('Ciudad 5', 'Ciudad 5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='profesorGuia',
            field=models.CharField(choices=[('Profesor 1', 'Profesor 1'), ('Profesor 2', 'Profesor 2'), ('Profesor 3', 'Profesor 3'), ('Profesor 4', 'Profesor 4'), ('Profesor 5', 'Profesor 5')], max_length=50),
        ),
    ]
